# Generated by Django 5.2.6 on 2025-10-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
